# Generated by Django 6.0 on 2025-12-09 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='allowed_hints',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='hints_used',
            field=models.IntegerField(default=0),
        ),
    ]
