# Generated by Django 6.0 on 2025-12-09 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_leaderboardentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeaderboardEntry',
        ),
    ]
