# Generated by Django 6.0 on 2025-12-09 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_leaderboardentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='display_name',
            field=models.CharField(blank=True, help_text="User's display name for leaderboard", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userscore',
            name='display_name',
            field=models.CharField(blank=True, help_text="User's display name for leaderboard", max_length=255, null=True),
        ),
    ]
