# Generated by Django 6.0 on 2025-12-10 04:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_gamesession_display_name_userscore_display_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiplayerSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('board_seed', models.CharField(max_length=64)),
                ('players', models.JSONField(default=list)),
                ('number_of_players', models.IntegerField(default=2)),
                ('scores', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('active', 'Active'), ('finished', 'Finished')], default='waiting', max_length=20)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('winners', models.JSONField(default=list)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10)),
                ('total_questions', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'created_at'], name='api_multipl_status_f8e28c_idx')],
            },
        ),
    ]
