# Generated by Django 6.0 on 2025-12-10 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_multiplayersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplayersession',
            name='join_code',
            field=models.CharField(blank=True, db_index=True, max_length=8, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='multiplayersession',
            index=models.Index(fields=['join_code'], name='api_multipl_join_co_1a9dcb_idx'),
        ),
    ]
