# Generated by Django 6.0 on 2025-12-08 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='question',
            name='cluebase_id',
            field=models.IntegerField(blank=True, help_text='Cluebase API clue ID', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='question',
            name='round',
            field=models.CharField(blank=True, help_text="Jeopardy round: 'J!' or 'DJ!'", max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='question',
            name='value',
            field=models.IntegerField(blank=True, help_text='Jeopardy dollar value', null=True),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['difficulty', 'category'], name='questions_q_difficu_b8a136_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['cluebase_id'], name='questions_q_cluebas_07dee5_idx'),
        ),
    ]
