# Generated by Django 6.0 on 2025-12-09 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_question_options_question_cluebase_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='question',
            name='questions_q_difficu_b8a136_idx',
        ),
        migrations.RemoveIndex(
            model_name='question',
            name='questions_q_cluebas_07dee5_idx',
        ),
        migrations.RemoveField(
            model_name='question',
            name='cluebase_id',
        ),
        migrations.RemoveField(
            model_name='question',
            name='round',
        ),
        migrations.RemoveField(
            model_name='question',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='question',
            name='value',
        ),
    ]
